DeclarationIndex source=tests/cases/modules/ok/project-compiler-main.ari modules=6 declarations=26
  Decl module=<root> kind=fn name=main visibility=private loc=tests/cases/modules/ok/project-compiler-main.ari:3:4 generics=[] params=[] return=i64 body=true
  Decl module=project_compiler kind=fn name=project_compiler::parse_score visibility=private loc=tests/cases/modules/ok/project_compiler.ari:20:4 generics=[] params=[result:ParseResult[Symbol]] return=i64 body=true
  Decl module=project_compiler kind=fn name=project_compiler::run visibility=pub loc=tests/cases/modules/ok/project_compiler.ari:24:8 generics=[] params=[] return=i64 body=true
  Decl module=project_compiler kind=fn name=project_compiler::span_score visibility=private loc=tests/cases/modules/ok/project_compiler.ari:12:4 generics=[] params=[span:Span] return=i64 body=true
  Decl module=project_compiler kind=fn name=project_compiler::symbol_score visibility=private loc=tests/cases/modules/ok/project_compiler.ari:16:4 generics=[] params=[symbol:Symbol] return=i64 body=true
  Decl module=project_compiler kind=use name=self::parser::ParseResult visibility=private loc=tests/cases/modules/ok/project_compiler.ari:10:5 alias=ParseResult
  Decl module=project_compiler kind=use name=self::source::Span visibility=private loc=tests/cases/modules/ok/project_compiler.ari:8:5 alias=Span
  Decl module=project_compiler kind=use name=self::symbols::Symbol visibility=private loc=tests/cases/modules/ok/project_compiler.ari:9:5 alias=Symbol
  Decl module=project_compiler::diag kind=enum name=project_compiler::diag::Severity visibility=pub loc=tests/cases/modules/ok/project_compiler/diag.ari:1:10 generics=[] cases=[Info, Error(i64)]
  Decl module=project_compiler::diag kind=fn name=project_compiler::diag::diagnostic visibility=pub loc=tests/cases/modules/ok/project_compiler/diag.ari:11:8 generics=[] params=[span:super::source::Span, code:i64] return=Diagnostic body=true
  Decl module=project_compiler::diag kind=fn name=project_compiler::diag::diagnostic_score visibility=pub loc=tests/cases/modules/ok/project_compiler/diag.ari:18:8 generics=[] params=[diagnostic:Diagnostic] return=i64 body=true
  Decl module=project_compiler::diag kind=struct name=project_compiler::diag::Diagnostic visibility=pub loc=tests/cases/modules/ok/project_compiler/diag.ari:6:12 generics=[] tuple=false fields=[span:super::source::Span, severity:Severity]
  Decl module=project_compiler::parser kind=enum name=project_compiler::parser::ParseResult visibility=pub loc=tests/cases/modules/ok/project_compiler/parse.ari:1:10 generics=[T] cases=[Parsed(T), Failed(super::diag::Diagnostic)]
  Decl module=project_compiler::parser kind=fn name=project_compiler::parser::make_state visibility=pub loc=tests/cases/modules/ok/project_compiler/parse.ari:12:8 generics=[] params=[symbol:super::symbols::Symbol] return=ParserState[super::symbols::Symbol] body=true
  Decl module=project_compiler::parser kind=fn name=project_compiler::parser::parse_score visibility=pub loc=tests/cases/modules/ok/project_compiler/parse.ari:28:8 generics=[] params=[result:ParseResult[super::symbols::Symbol]] return=i64 body=true
  Decl module=project_compiler::parser kind=fn name=project_compiler::parser::run_state visibility=pub loc=tests/cases/modules/ok/project_compiler/parse.ari:21:8 generics=[] params=[state:ParserState[super::symbols::Symbol]] return=ParseResult[super::symbols::Symbol] body=true
  Decl module=project_compiler::parser kind=struct name=project_compiler::parser::ParserState visibility=pub loc=tests/cases/modules/ok/project_compiler/parse.ari:6:12 generics=[T] tuple=false fields=[file:super::source::SourceFile, current:T, diagnostic:super::diag::Diagnostic]
  Decl module=project_compiler::source kind=fn name=project_compiler::source::source_file visibility=pub loc=tests/cases/modules/ok/project_compiler/source.ari:15:8 generics=[] params=[id:i64, span:Span] return=SourceFile body=true
  Decl module=project_compiler::source kind=fn name=project_compiler::source::span visibility=pub loc=tests/cases/modules/ok/project_compiler/source.ari:11:8 generics=[] params=[start:i64, end:i64] return=Span body=true
  Decl module=project_compiler::source kind=fn name=project_compiler::source::span_len visibility=pub loc=tests/cases/modules/ok/project_compiler/source.ari:19:8 generics=[] params=[span:Span] return=i64 body=true
  Decl module=project_compiler::source kind=struct name=project_compiler::source::SourceFile visibility=pub loc=tests/cases/modules/ok/project_compiler/source.ari:6:12 generics=[] tuple=false fields=[id:i64, span:Span]
  Decl module=project_compiler::source kind=struct name=project_compiler::source::Span visibility=pub loc=tests/cases/modules/ok/project_compiler/source.ari:1:12 generics=[] tuple=false fields=[start:i64, end:i64]
  Decl module=project_compiler::symbols kind=fn name=project_compiler::symbols::private_bias visibility=private loc=tests/cases/modules/ok/project_compiler/symbols.ari:13:4 generics=[] params=[] return=i64 body=true
  Decl module=project_compiler::symbols kind=fn name=project_compiler::symbols::symbol visibility=pub loc=tests/cases/modules/ok/project_compiler/symbols.ari:5:8 generics=[] params=[id:i64] return=Symbol body=true
  Decl module=project_compiler::symbols kind=fn name=project_compiler::symbols::symbol_score visibility=pub loc=tests/cases/modules/ok/project_compiler/symbols.ari:9:8 generics=[] params=[symbol:Symbol] return=i64 body=true
  Decl module=project_compiler::symbols kind=struct name=project_compiler::symbols::Symbol visibility=pub loc=tests/cases/modules/ok/project_compiler/symbols.ari:1:12 generics=[] tuple=false fields=[id:i64]
